### ISSUE TITLE
loading problem 

### ISSUE THREAD

**Issue by TheeFlyingPenguin** [Miki-Tellurium/GrateBlocks#1] opened 2023-06-22 18:41 UTC
I just got the mode and offline works fine , but when I try to add it to a server it doesn't load 

https://gist.github.com/TheeFlyingPenguin/4d8028d93b028540ac5379d5a64c5728

**Comment by Miki-Tellurium** [comment] 2023-06-23 14:42
Crash was caused by client-only method being called on server side. Fixed in version 1.5.1

**Comment by TheeFlyingPenguin** [comment] 2023-06-23 14:46
I mean that is the version I have 1.5.1 
cuz I m playing on a 1.20 Minecraft version of forge

**Comment by Miki-Tellurium** [comment] 2023-06-23 14:51
No, the version you were using is 1.5.0 as stated in the log you posted. I updated the mod to 1.5.1 to fix that crash and removed the faulty version from modrinth.

**Comment by TheeFlyingPenguin** [comment] 2023-06-23 14:54
whoa, wait a second that s true, that was weird I thought as I should have. I'll try the 1.5.1 real quick and I will get back with feedback :) 
thanks for the prompt answer

**Comment by TheeFlyingPenguin** [comment] 2023-06-23 15:02
works as stated, thanks so much for the quick check-up, the mode is amazing and on the site, everything was so explicit, keep up the good work 💯

**Comment by Miki-Tellurium** [comment] 2023-06-23 15:06
Thank you for the feedback

**Closed as completed by Miki-Tellurium** 2023-06-23 15:06 UTC
